-- Migration 019b (Step 2): Seed Foundation Models tools
-- Run AFTER migration_019 has been committed.

insert into public.tools (name, category, description, url, pricing, best_for, color, letter, is_published, is_featured, order_index)
values
  ('GPT-4o',         'Foundation Models', 'OpenAI''s flagship multimodal model — handles text, images, audio, and code in one unified model.',       'https://openai.com/gpt-4o',         'Free tier + API pay-as-you-go',   'General-purpose tasks, vision, coding, and chat',          '#10A37F', 'G', true, true,  1),
  ('Claude 3.7',     'Foundation Models', 'Anthropic''s frontier model with extended thinking and strong long-context reasoning.',                    'https://claude.ai',                 'Free tier + Pro $20/mo',          'Long documents, nuanced writing, and complex analysis',     '#D97757', 'C', true, false, 2),
  ('Gemini 1.5 Pro', 'Foundation Models', 'Google DeepMind''s model with a 1M-token context window — best for huge documents and multimodal inputs.','https://gemini.google.com',         'Free tier + Advanced $20/mo',     'Massive context tasks, Google Workspace integration',        '#4285F4', 'G', true, false, 3),
  ('Llama 3',        'Foundation Models', 'Meta''s open-weight model — run it locally, fine-tune it, or access it via hosted providers.',             'https://llama.meta.com',            'Free (open weights)',             'Self-hosted AI, privacy-sensitive workloads, fine-tuning',  '#0064E0', 'L', true, false, 4),
  ('Mistral Large',  'Foundation Models', 'Efficient European frontier model with strong multilingual and reasoning capabilities.',                    'https://mistral.ai',                'API pay-as-you-go',               'Multilingual tasks and cost-efficient inference',            '#FF7000', 'M', true, false, 5),
  ('Grok 3',         'Foundation Models', 'xAI''s model with real-time X/Twitter data access and strong STEM reasoning.',                             'https://grok.x.ai',                 'Free with X Premium',             'Real-time web data, STEM problems, and research',            '#1DA1F2', 'G', true, false, 6),
  ('Command R+',     'Foundation Models', 'Cohere''s enterprise-grade model optimised for RAG and tool use in production pipelines.',                 'https://cohere.com',                'API pay-as-you-go',               'Enterprise RAG, search grounding, and tool-calling',         '#39594A', 'C', true, false, 7),
  ('DeepSeek V3',    'Foundation Models', 'Open-source frontier model matching top closed models at a fraction of the inference cost.',               'https://deepseek.com',              'Free (open weights) + hosted API','Cost-efficient reasoning and coding tasks',                  '#4D6BFE', 'D', true, false, 8);
