-- ============================================
-- Sample seed content — run after schema.sql
-- ============================================

-- News
insert into public.news (title, body, tag, action_text, is_featured) values
('ChatGPT now reads 50 PDFs in one chat', 'Useful for synthesizing reports, vendor proposals, or research. Drop a folder of PDFs and ask for a single executive summary.', 'FEATURE', 'Try with your last meeting deck', true),
('AI agents are hitting the workplace', 'Companies are starting to deploy task-completing agents in HR and Sales. The shift from "AI as advisor" to "AI as doer" is happening faster than expected.', 'TREND', 'Read 3-min explainer', true),
('60-second tip: use system prompts', 'Set context once at the top of your chat — saves you re-explaining every prompt. Most chat apps now support a "custom instructions" or "system" field.', 'QUICK WIN', 'Try this in ChatGPT now', false),
('Claude 4.7 benchmarks released', 'Anthropic released Claude 4.7 with notable improvements on long-context reasoning and coding tasks.', 'MODEL', 'Compare against your current AI', false),
('EU AI Act phase 2 enforcement begins', 'New compliance requirements kick in for high-risk AI systems. Affects HR tools, hiring AI, biometric systems.', 'POLICY', 'Check if your tools comply', false);

-- Videos
insert into public.videos (title, creator, duration, category, youtube_url, is_featured) values
('10 AI tools that actually save time at work', 'Matt Wolfe', '8:42', 'Tools', 'https://www.youtube.com/results?search_query=matt+wolfe+ai+tools', true),
('Why reasoning models matter — explained simply', 'AI Explained', '14:20', 'Deep dives', 'https://www.youtube.com/results?search_query=ai+explained+reasoning+models', false),
('Building agents that book your meetings', 'Varun Mayya', '11:05', 'Tutorials', 'https://www.youtube.com/results?search_query=varun+mayya+ai+agents', false),
('Everything new in AI this week', 'Wes Roth', '12:30', 'News', 'https://www.youtube.com/results?search_query=wes+roth+ai+news', false),
('Excel + ChatGPT: 5 power moves', 'Build Fast with AI', '7:15', 'Tutorials', 'https://www.youtube.com/results?search_query=excel+chatgpt+power+moves', false);

-- Tools
insert into public.tools (name, category, description, url, tag, is_product_of_day) values
('Gamma', 'PPT', 'AI deck generator — fastest way to go from notes to a polished deck', 'https://gamma.app', 'Best overall', true),
('Beautiful.ai', 'PPT', 'Smart slide design with auto-layout', 'https://beautiful.ai', null, false),
('Tome', 'PPT', 'Narrative-style decks with AI', 'https://tome.app', null, false),
('Microsoft Copilot', 'Excel', 'Inside Microsoft 365 — Excel formulas, analysis, charts', 'https://copilot.microsoft.com', 'Best for office', false),
('Rows', 'Excel', 'AI-native spreadsheet', 'https://rows.com', null, false),
('Midjourney', 'Image', 'Best image quality for creative visuals', 'https://midjourney.com', 'Best quality', false),
('Ideogram', 'Image', 'Best for text inside images', 'https://ideogram.ai', null, false),
('Veo 3', 'Video', 'Google text-to-video model', 'https://deepmind.google/technologies/veo/', 'Best in class', false),
('Runway', 'Video', 'Pro video editing AI', 'https://runwayml.com', null, false),
('ElevenLabs', 'Voice', 'Voice cloning + TTS, most realistic', 'https://elevenlabs.io', 'Most realistic', false),
('Cursor', 'Coding', 'AI code editor', 'https://cursor.com', 'Devs love it', false),
('Perplexity', 'Research', 'Cited search + answers', 'https://perplexity.ai', 'Best for sources', false),
('NotebookLM', 'Research', 'Audio + mindmaps from your documents', 'https://notebooklm.google', null, false);

-- Glossary
insert into public.glossary (term, definition) values
('Agent', 'AI that can take actions on its own — search the web, run code, click buttons.'),
('Artifact', 'A standalone file/output (code, doc, image) generated by AI alongside its chat reply.'),
('API', 'A way for apps to talk to AI models programmatically.'),
('Context Window', 'How much text the AI can "remember" in one conversation. Older messages drop off when full.'),
('Embedding', 'Turning text into numbers so AI can find similar meaning.'),
('Fine-tuning', 'Training a base model further on your specific data.'),
('Hallucination', 'When AI confidently invents a wrong fact.'),
('MCP', 'Model Context Protocol — a standard way to plug AI into tools, files, and data sources.'),
('Markdown (MD)', 'A simple text format with #, **bold**, lists. AI loves it because it''s clean.'),
('Prompt', 'The instruction you give the AI.'),
('RAG', 'Retrieval-Augmented Generation — AI looks up your documents before answering.'),
('Reasoning Model', 'A model that "thinks step by step" before answering. Slower but smarter on hard problems.'),
('Token', 'A chunk of text (~3/4 of a word). Models charge per token.'),
('Tool Calling', 'When AI decides to use a tool — calculator, web search, your calendar.');

-- Lessons + Questions
insert into public.lessons (id, title, description, order_index) values
('11111111-1111-1111-1111-111111111111', 'Tokens & context windows', 'Why your AI "forgets" — and how to use it smartly.', 1),
('22222222-2222-2222-2222-222222222222', 'What is a prompt?', 'The fundamentals of talking to AI clearly.', 0);

insert into public.questions (lesson_id, question_text, options, correct_index, explanation, order_index) values
('11111111-1111-1111-1111-111111111111', 'What is a context window?',
  '["Where you type your prompt", "How much text the AI can ''remember'' at once", "A premium feature", "The output screen"]'::jsonb,
  1, 'It''s the model''s working memory — once full, older messages get dropped.', 0),
('11111111-1111-1111-1111-111111111111', 'Which prompt is clearer?',
  '["Write something about leadership", "Write a 200-word LinkedIn post for senior managers about giving feedback in remote teams. Tone: direct."]'::jsonb,
  1, 'Specific role, length, audience, tone = better output.', 1),
('11111111-1111-1111-1111-111111111111', 'When AI confidently invents a fact, this is…',
  '["Bias", "Hallucination", "Drift", "Overfitting"]'::jsonb,
  1, 'Hallucination = confident but wrong. Verify high-stakes facts.', 2);

-- Apply task with steps
insert into public.apply_tasks (id, title, category, description, tool_name, prompt_template, duration_min, xp_reward, is_daily, order_index) values
('33333333-3333-3333-3333-333333333333',
  'Meeting notes → 5-slide deck',
  'PPT',
  'Turn raw meeting notes into a clean board-ready deck using Gamma + a prompt that works every time.',
  'Gamma',
  'You are a deck designer. Turn the meeting notes below into a 5-slide presentation:
- Slide 1: Title + 1-line context
- Slide 2: Key decisions made (max 4 bullets)
- Slide 3: Risks identified (max 3 bullets)
- Slide 4: Next steps with owners
- Slide 5: Open questions

Use plain language. No fluff. Each bullet ≤ 12 words.

Meeting notes:
{user_input}',
  5, 30, true, 1);

insert into public.apply_task_steps (task_id, step_type, title, body, order_index) values
('33333333-3333-3333-3333-333333333333', 'intro', 'Meeting notes → 5-slide deck', 'You''ll learn how to turn raw notes into a clean board-ready deck — using a prompt that works every time.', 0),
('33333333-3333-3333-3333-333333333333', 'input', 'Paste your meeting notes', 'Use real notes. We''ll wrap them in the perfect prompt.', 1),
('33333333-3333-3333-3333-333333333333', 'prompt', 'Copy this prompt', 'Tailored to your notes. Try memorising the structure — you''ll reuse it.', 2),
('33333333-3333-3333-3333-333333333333', 'paste-guide', 'Open Gamma & paste it here', 'Go to gamma.app → click "+ New AI presentation" → paste your prompt → click Generate.', 3),
('33333333-3333-3333-3333-333333333333', 'evaluate', 'Did Gamma do its job?', 'Tick what''s in your deck: decisions, risks, next steps with owners.', 4),
('33333333-3333-3333-3333-333333333333', 'improve', 'Make it sharper', 'Try follow-up prompts: "Make every bullet ≤ 8 words", "Tone: more direct", "Add a timeline slide".', 5),
('33333333-3333-3333-3333-333333333333', 'log', 'Did you use this at work?', 'Honest answer. Counts toward your skill score.', 6);
