-- Run AFTER migration_003_resources.sql
insert into public.resources (name, provider, description, url, category, is_featured, order_index) values
('Anthropic Academy', 'Anthropic',
  'Free, structured learning to build practical AI fluency. Workshops, courses, and certificates. Useful for individuals and teams using Claude for personal projects. Includes an AI Fluency newsletter.',
  'https://www.anthropic.com/learn', 'Academy', true, 1),
('Claude Use-Cases', 'Anthropic',
  'Practical inspiration library showing what users can do with Claude across research, writing, coding, analysis, and everyday tasks. Browse examples by category, feature, and product.',
  'https://claude.com/resources/use-cases', 'Use Cases', true, 2),
('Claude Tutorials', 'Anthropic',
  'Hands-on learning library for building Claude skills through written guides and video lessons. Covers AI fluency, education, engineering, finance, HR, marketing, sales, research, projects, connectors, skills, Claude Code, Claude Cowork, and Claude.ai.',
  'https://claude.com/resources/tutorials', 'Tutorials', false, 3),
('Claude Courses', 'Anthropic',
  'Structured learning paths with video lessons, assessments, and quizzes covering AI fluency, Claude development, Claude Code, Claude Cowork, Claude Platform, and MCP. Filter courses by product and category.',
  'https://claude.com/resources/courses', 'Courses', false, 4),
('OpenAI Academy', 'OpenAI',
  'Free learning and community hub for AI literacy and practical AI skills. Live events, recorded content, community spaces, stories, and resources for builders, educators, work users, small businesses, nonprofits, and government teams.',
  'https://academy.openai.com/', 'Academy', true, 5),
('Google AI Essentials', 'Google',
  'Beginner-friendly course covering generative AI fundamentals. Self-paced with practical examples for everyday work tasks.',
  'https://grow.google/ai-essentials/', 'Courses', false, 6),
('Microsoft AI Skills Hub', 'Microsoft',
  'Free training paths and certifications for AI literacy, Copilot usage, and AI in business. Includes workplace-focused content.',
  'https://learn.microsoft.com/en-us/training/career-paths/ai-engineer', 'Courses', false, 7),
('DeepLearning.AI', 'DeepLearning.AI',
  'Andrew Ng''s platform with short courses on prompt engineering, LLMs, and applied AI. Mix of free and paid courses.',
  'https://www.deeplearning.ai/short-courses/', 'Courses', false, 8);
